apiVersion: v1
kind: Pod
metadata:
  name: sametklstoolbox-pod
spec:
  containers:
  - name: sametklstoolbox
    image: sametkeles/sametklstoolbox:latest
    command: ["sleep"]
    args: ["infinity"]
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"